### ISSUE TITLE
Transpile LESS to CSS with webpack, modularize library styles and change library classnames and project name

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/scss-helper-library#5]
#### Tasks
Currently, less code is transpiled to CSS with this and also watched with nodemon in the package.json: 
````
"less": "nodemon --exec lessc src/less/styles.less src/css/styles.css",
```` 
Webpack configurations have just been added not too long for development and production, though not completed yet. Things to consider and work on in this task:
- [x] Transpile LESS to CSS using webpack instead - **done!**
- [x] Split less code for library and the simple page that shows up when port opens up in the browser -**done!**
- [x] We have separate less files referenced in the styles.less file: Is it possible to have the css files generated (library.css) split into separate CSS files like that?
(Thinking of separating our CSS bundles so that users have the choice to only import what they need).
